projet_voxel_core:
    resource: "@ProjetVoxelCoreBundle/Resources/config/routing.yml"
    prefix:   /

projet_voxel_emploi:
    resource: "@ProjetVoxelEmploiBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: ProjetVoxelUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
