projet_voxel_emploi_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProjetVoxelEmploiBundle:Default:index }
projet_voxel_emploi_createEntreprise:
    path: /company/create
    defaults: {_controller: ProjetVoxelEmploiBundle:Company:create}
projet_voxel_emploi_listCompany:
    path: /company/list
    defaults: {_controller: ProjetVoxelEmploiBundle:Company:list}