projet_voxel_emploi_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProjetVoxelEmploiBundle:Default:index }

projet_voxel_emploi_createEntreprise:
    path: /company/create
    defaults: {_controller: ProjetVoxelEmploiBundle:Company:create}

projet_voxel_emploi_listCompany:
    path: /company/list
    defaults: {_controller: ProjetVoxelEmploiBundle:Company:list}

projet_voxel_emploi_uneCompany:
    path: /company/{id}
    defaults: {_controller: ProjetVoxelEmploiBundle:Company:displayOne}

projet_voxel_emploi_editEntreprise:
    path: /company/{id}/edit
    defaults: {_controller: ProjetVoxelEmploiBundle:Company:edit}

projet_voxel_emploi_createJob:
    path: /company/{id}/edit/createJob
    defaults: {_controller: ProjetVoxelEmploiBundle:Job:create}