projet_voxel_ventes_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProjetVoxelVentesBundle:Default:index }

projet_voxel_ventes_add_catalogue_item:
    path: /{bankId}/catalogue/additem
    defaults: { _controller: ProjetVoxelVentesBundle:Catalogue:addItem }

projet_voxel_ventes_catalogue:
    path: /{bankId}/catalogue
    defaults: { _controller: ProjetVoxelVentesBundle:Catalogue:view }

projet_voxel_ventes_a_catalogue_item:
    path: /{bankId}/catalogue/item/{catalogueItemId}
    defaults: { _controller: ProjetVoxelVentesBundle:Catalogue:aCatalogueItem }
