services:
#    projet_voxel_user.example:
#        class: ProjetVoxel\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    projet_voxel_user.registration_completed:
        class: ProjetVoxel\UserBundle\EventListener\RegistrationCompletedListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_subscriber }
